### ISSUE TITLE
[95] tD.Tracking: SPIKE learning database API (13)

### ISSUE THREAD

**Issue by Redmayspecial** [unfoldingWord-dev/translationDatabaseWeb#109]
**Spike:**
Learn how to interact with the existing database.

**Checklist:**
- [x] Query the database through models
- [x] Save form as a model to the database
- [x] Learn the model-based query language (https://docs.djangoproject.com/en/1.8/ref/models/expressions/)

**Definition of Done:**
* Being able to pull information out
* Being able to put information in

**Comment by Redmayspecial** [comment]
Check with Steve, Shannon, or Patrick for advice

**Comment by vleong2332** [comment]
@Redmayspecial 
Checklist:
- [ ] Query the database using models
- [x] Save form as a model to the database
- [ ] Learn the model-based query language
