### ISSUE TITLE
[99]tD.Tracking: SPIKE learning Django Form API (8)

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#111]
## Spike
Learn how to utilize Django to create forms from existing models

### Checklist:

- [x] Create a model and make a form based on that model
- [x] Create a model with relationship field and create a form based on that
- [x] How to handle form submission?
- [x] Customize the template of the form
- [x] Customize the type of input for a field
- [x] Add stylesheet to the form
- [x] Add extra styles
- [x] What's the best way to sanitize user input
- [x] Learn CreateView
- [x] Learn UpdateView
- [x] Learn the existing code from publishing request form
   - [x] `def __init__():`
   - [x] `if self.instance.pk:`
   - [x] `def clean_language(self):`
   - [x] `def clean(self):`
- [x] How to use multiple text inputs to create entry for ManyToMany Field?
- [x] How to detect logged in user?
- [x] Form and Field validation

## Definition of Done
Being able to create a form that submits data.
Being able to create fields, labels, and help text from created models.
