### ISSUE TITLE
[95]tD.Tracking: SPIKE learning DB relations (13)

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#137]
## Spike
Learn how to make many-to-many relationships through Django, if possible.

### Checklist

- [x] Learn about relationship fields
- [x] Learn about how many-to-many relationship is rendered in form
- [x] Think through on how to improve the many-to-many relationship form UI

## Definition of Done
Being able to create a model/table that reflects many-to-many relationship
Being able to execute a test case scenario linking multiple events to multiple translators/materials.
