### ISSUE TITLE
[91]tD.Tracking: SPIKE Low fidelity prototype/wireframe of the form (8)

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#138]
## Description

Present first draft of prototype to Paul Foxworthy to get feedback in regards to requirements and other fields.

### Checklist

- [x] Mock up different forms
- [x] Mock up home page
- [x] Mock up detail pages
- [x] Mock up success pages 

## Definition of Done

Have a digital version of the form prototype.
