### ISSUE TITLE
tD.Tracking: Test criteria for adding new project

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#145]
## Description

Establish criteria for testing "add a new project" functionality.

#### Criteria
- [ ] Solve `ProgrammingError: relation "auth_user" does not exist` when running `./manage.py test td.tracking`
- [ ] Test for charter models
- [ ] Test for charter urls
- [ ] Test for charter views
- [ ] Test for charter templates

**Comment by vleong2332** [comment]
Detailed list is in local OneNote
