### ISSUE TITLE
[70] td.tracking: Apply appropriate/conventional code style

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#157]
## Description

Adjust the code in td.tracking to comply with `flake8 td`

## Checklist

- [x] Read [https://www.python.org/dev/peps/pep-0008/]
- [x] Apply style to models.py
- [x] Apply style to views.py
- [x] Apply style to urls.py
- [x] Apply style to forms.py
- [x] Apply style to tests.py

## Definition of Done

Running `flake8 td` in the console does not produce any warning or error.
