### ISSUE TITLE
[80] td.tracking: Test for Charter model

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#160]
## Description

Write automated tests in Django for the Charter model.

## Checklist

- [x] "language" is required and must be unique
- [x] "countries" is required and must be a valid date
- [x] "start_date" is required and must be a valid date
- [x] "end_date" is required and must be a valid date
- [x] "number" is required and must be 10 characters or less
- [x] "lead_dept" is required and must be one of the departments listed
- [x] "contact_person" is required and must be 200 characters or less
- [x] "created_at" is required and must default to the date and time of submission
- [x] "created_by" is required and must default to logged-in user's username
- [x] It should identify itself as the associated language's code

## Definition of Done

Charter model passes all tests.
