### ISSUE TITLE
[60] td.tracking: working basic homepage for tracking

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#162]
## Checklist

- [x] localhost:8000/tracking/ page throws an error.
- [x] Apply the base style
- [x] Display the table for existing projects
