### ISSUE TITLE
td.tracking: Test for Charter urls

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#164]
## Checklist

- [x] "charter/add" needs to be routed to "charter_add" class
- [x] "charter/update/<pk>" needs to be routed to charter_update class
- [x] "charter/add/success/<pk>" needs to be routed to the charter_add_success function
- [x] "charter/add/success/<pl>" must route to invalid if it doesn't come from a form submission
- [x] Invalid urls must be routed to a 404 page
- [x] Valid urls with invalid params must be routed to a 404 page
- [x] Valid urls must return status 200
