### ISSUE TITLE
td.tracking: Test for charter views

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#165]
## Checklist

- [x] charter_add must only allow logged-in user
- [x] charter_add template must have the title 'New Charter Form'
- [x] charter_add must initialize start_date as today's date
- [x] charter_add must initialize created_by with user's username
- [x] charter_update must only allow logged-in user
- [x] charter_update must use the right template file
- [x] charter_add_success must only allow logged-in user
- [x] charter_add_success must raise 404 if the object is not found
- [x] charter_add_success must load the right template file
- [x] charter_add_success must pass the right context
