### ISSUE TITLE
td.tracking: Test for charter form

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#166]
## Checklist

- [x] language field must be a text input
- [x] language field must have the right attributes
- [x] All fields are required
- [x] start_date must be a SelectDateWidget
- [x] start_date must have the right class
- [x] end_date must be a SelectDateWidget
- [x] end_date must have the right class
- [x] Name must not be an empty string
- [x] Valid form should be submitted (resulting model should exist)
