### ISSUE TITLE
td.tracking: Test for home view

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#185]
## Checklist

- [x] Valid URL returns 200
- [x] Invalid URL returns 404
- [x] Valid response contains the heading: Tracking Dashboard
