### ISSUE TITLE
Test out app tracking on td-demo

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#234]
## Description

Based on pull request #231 

Play around with the [tracking app] (td-demo.unfoldingword.org/tracking/) and see if anything seems out of order.

## Tasks

- [x] Create a translation project charter
- [x] Create a duplicate project charter
- [x] View the language/project detail
- [x] Edit a project charter
- [x] Create an event for existing charter
- [x] Create an event for non-existing charter
- [x] View the list of events in language/project detail
- [x] View the language/project detail as logged-out user
- [x] View the language/project detail as logged-in user
