### ISSUE TITLE
td.tracking: Adjust routing to and from the form creations

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#241]
## Checklist

- [x] lang list --> lang/proj detail --> add project --> project list
- [x] lang list --> lang/proj detail --> edit project --> lang/project detail
- [x] lang list --> lang/proj detail  --> add event --> lang/project detail
- [x] lang list --> lang/proj detail --> event detail --> edit event --> event detail

**Comment by vleong2332** [comment]
Added buttons on success page for charter and event to give user options on where to go next.
