### ISSUE TITLE
td.tracking: Form to create a single event for multiple languages

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#253]
- [x] Create new charter on a modal
- [x] Add and remove charter fields
- [x] Successful validation and submission on form 1
- [x] Basic event form UI
- [x] Event form POST handling
- [x] Successful validation and submission on form 2
- [x] Saving to database
- [x] Success page and routing
- [x] Manual testing and confirmation
