### ISSUE TITLE
td.tracking: Form to create multiple charters

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#254]

**Comment by vleong2332** [comment]
## Question:

Will this still be a TOP priority once #253 is done?

**Comment by vleong2332** [comment]
## To-Do:
- [ ] Clear values when adding more charter after POST
- [ ] Get initial values on start date
- [ ] Duplicated wanted values pre-POST
- [ ] Clear error class and message when adding more charter after POST
- [ ] Decide on the form heading
- [ ] Submit a valid form and look at the POSTed data
- [ ] Save to the database
