### ISSUE TITLE
td.tracking: Use-case scenario

### ISSUE THREAD

**Issue by vleong2332** [unfoldingWord-dev/translationDatabaseWeb#264]
- [x] I want to look at the list of on-going projects
- [x] I want to fill out a form for an event that involves 2 languages
- [x] I want to create a translation project charter for (choose a language)
- [x] After I created a project charter, I want to see that info that I just put in
- [x] I want to submit and event form for (choose a language)
- [x] After I created the event form, I want to look at the info that I just put in.
